<?php

use Aternos\Codex\Log\File\PathLogFile;
use Aternos\Codex\Minecraft\Detective\Detective;

date_default_timezone_set('UTC');
require_once __DIR__ . '/../vendor/autoload.php';

$input = __DIR__ . "/data/";

if (!str_ends_with($input, "/")) {
    $input .= "/";
}

$testFunctions = [];
$inputFiles = new RegexIterator(new RecursiveIteratorIterator(new RecursiveDirectoryIterator($input)), '/.+\.log/i', RegexIterator::GET_MATCH);
foreach ($inputFiles as $inputFilePath => $inputFile) {
    $dirname = dirname($inputFilePath);
    $basename = basename($inputFilePath, ".log");

    $testFunctions[] = (new \Aternos\Codex\Minecraft\Test\Logs\TestLog($inputFilePath))->getTestFunction();

    $outputPath = $dirname . "/" . $basename . ".json";

    $logFile = new PathLogFile($inputFilePath);
    $detective = new Detective();
    $detective->setLogFile($logFile);
    $log = $detective->detect();
    $log->parse();

    $outputJson = json_encode($log, JSON_PRETTY_PRINT);

    if (file_exists($outputPath) && file_get_contents($outputPath) === $outputJson) {
        continue;
    }
    file_put_contents($outputPath, $outputJson);
    echo "Updated '" . $basename . "'" . PHP_EOL;
}

$testFunctionsOutput = trim(implode(PHP_EOL, $testFunctions));
$testClass = <<<EOF
<?php
/** @noinspection SpellCheckingInspection */

namespace Aternos\Codex\Minecraft\Test\Logs;

use Exception;

/**
 * Class AutoLogsTest
 * 
 * This class is auto-generated by the generate-tests.php script.
 * 
 * @package Aternos\Codex\Minecraft\Test\Logs 
 */
class AutoLogsTest extends \PHPUnit\Framework\TestCase
{
    {$testFunctionsOutput}
}
EOF;
$testClassPath = __DIR__ . "/tests/Logs/AutoLogsTest.php";
if (!file_exists($testClassPath) || file_get_contents($testClassPath) !== $testClass) {
    file_put_contents($testClassPath, $testClass);
    echo "Updated test class AutoLogsTest.php" . PHP_EOL;
}
